name: Auto Deploy

on:
  push:
    branches:
      - '**'

jobs:
  auto-pr-and-deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'Marcuse-69'
    steps:
      - uses: actions/checkout@v2

      - name: Create PR if none exists
        if: github.event_name == 'push' && !github.event.pull_request
        run: |
          PR_BRANCH=${GITHUB_REF#refs/heads/}
          if [ "$PR_BRANCH" != "main" ]; then
            gh pr create --base main --head $PR_BRANCH --title "Auto PR from $PR_BRANCH" --body "Automated PR creation from Workspace"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Approve PR
        if: github.event.pull_request
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Merge PR
        if: github.event.pull_request
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  log-deployment:
    needs: auto-pr-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Log Deployment
        run: |
          echo "Deployment triggered at $(date)" >> deployment.log
          echo "Changes auto-processed from Workspace" >> deployment.log