name: Auto Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'Marcuse-69' # Only for repository owner
    steps:
      - name: Auto Approve PR
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE"}'

      - name: Auto Merge PR
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
            -d '{"merge_method":"squash"}'

  log-deployment:
    needs: auto-approve-and-merge
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment Log
        run: |
          echo "Deployment triggered at $(date)" >> deployment.log
          echo "PR #${{ github.event.pull_request.number }} auto-merged" >> deployment.log